configs:
  Development_Debug: debug
  Development_Release: release
  Tests: debug
  Production_Debug: debug
  Production_Release: release


configFiles:
  Development_Debug: ../ConfigurationFiles/Development.xcconfig
  Development_Release: ../ConfigurationFiles/Development.xcconfig
  Tests: ../ConfigurationFiles/Development.xcconfig
  Production_Debug: ../ConfigurationFiles/Production.xcconfig
  Production_Release: ../ConfigurationFiles/Production.xcconfig


settings:
  base:
    CURRENT_PROJECT_VERSION: 1
    IPHONEOS_DEPLOYMENT_TARGET: 17.0
    MARKETING_VERSION: 0.0.1
    PRODUCT_NAME: "$(TARGET_NAME)"
    SWIFT_STRICT_CONCURRENCY: "complete"
    ASSETCATALOG_COMPILER_GENERATE_SWIFT_ASSET_SYMBOL_EXTENSIONS: NO
    ASSETCATALOG_COMPILER_GENERATE_ASSET_SYMBOLS: NO
    GENERATE_INFOPLIST_FILE: YES
    SWIFT_STRICT_CONCURRENCY: complete
    CODE_SIGN_STYLE: NO
    INFOPLIST_FILE: "Info.plist"

  configs:
    Development_Debug:
      APP_DISPLAY_NAME: "AirQuality Dev"
      PRODUCT_BUNDLE_IDENTIFIER: "com.air.quality.dev"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
    Development_Release:
      APP_DISPLAY_NAME: "AirQuality Dev"
      PRODUCT_BUNDLE_IDENTIFIER: "com.air.quality.dev"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "DEBUG"
    Tests:
      APP_DISPLAY_NAME: "AirQuality"
      PRODUCT_BUNDLE_IDENTIFIER: "com.air.quality.dev"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "PROD"
    Production_Debug:
      APP_DISPLAY_NAME: "AirQuality"
      PRODUCT_BUNDLE_IDENTIFIER: "com.air.quality"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "PROD"
    Production_Release:
      APP_DISPLAY_NAME: "AirQuality"
      PRODUCT_BUNDLE_IDENTIFIER: "com.air.quality"
      SWIFT_ACTIVE_COMPILATION_CONDITIONS: "PROD"
      VALIDATE_PRODUCT: YES
