excluded:
  - AirQualityTests/*
  - AirQuality/Localizable/*

opt_in_rules:
  - all

disabled_rules:
  - anonymous_argument_in_multiline_closure
  - anyobject_protocol # It's deprecated and will be removed in a future release.
  - class_delegate_protocol
  - conditional_returns_on_newline
  - discouraged_none_name
  - discouraged_optional_boolean
  - discouraged_optional_collection
  - explicit_acl
  - explicit_enum_raw_value
  - explicit_top_level_acl
  - explicit_type_interface
  - extension_access_modifier
  - file_header
  - file_name
  - file_types_order
  - function_default_parameter_at_end
  - ibinspectable_in_extension
  - indentation_width
  - inert_defer # It's deprecated and will be removed in a future release.
  - legacy_multiple
  - legacy_objc_type
  - let_var_whitespace
  - local_doc_comment
  - missing_docs
  - multiline_arguments_brackets
  - no_extension_access_modifier
  - no_grouping_extension
  - no_magic_numbers
  - nslocalizedstring_key
  - pattern_matching_keywords
  - prefer_nimble
  - prefer_self_in_static_references
  - prefixed_toplevel_constant
  - prohibited_interface_builder
  - reduce_into
  - redundant_self_in_closure
  - redundant_type_annotation
  - required_deinit
  - sorted_enum_cases
  - sorted_imports
  - static_operator
  - strict_fileprivate
  - strong_iboutlet
  - superfluous_else
  - switch_case_on_newline
  - todo
  - toggle_bool
  - trailing_closure
  - type_contents_order
  - unavailable_function
  - unused_capture_list # It's deprecated and will be removed in a future release.
  - vertical_whitespace_between_cases
  - vertical_whitespace_opening_braces
  - void_return
  - xct_specific_matcher
  - trailing_whitespace

attributes:
  always_on_line_above:
    - "@MainActor"
    - "@discardableResult"
  always_on_same_line:
    - "@objc"
    - "@Injected"

line_length:
  warning: 200
  error: 600

file_length:
  warning: 500
  error: 800

type_body_length:
  warning: 300
  error: 400

type_name:
  min_length: 3 
  max_length:
    warning: 60
    error: 70

identifier_name:
  min_length: 2
  max_length: 50
  allowed_symbols: ["_"]
  excluded:
    ["x", "y", "i"]

cyclomatic_complexity:
  ignores_case_statements: true
  warning: 10
  error: 20

large_tuple:
  warning: 4
  error: 5

modifier_order:
  preferred_modifier_order:
    [acl, final, override, setterACL, dynamic, mutators, lazy, required, convenience, typeMethods, owned]

multiline_arguments:
  only_enforce_after_first_closure_on_first_line: true

void_function_in_ternary:
  severity: error

blanket_disable_command:
  severity: error

superfluous_disable_command:
  severity: error

nesting:
  type_level: 5

reporter: "xcode"
