name: AirQuality


options:
  usesTabs: false
  transitivelyLinkDependencies: true
  groupSortPosition: bottom
  groupOrdering:
    - order: [AirQuality, AirQualityTests]
  developmentLanguage: pl


fileGroups:
  - AirQuality
  - AirQualityTests


include: [.xcodegen/targets.yml, .xcodegen/schemes.yml, .xcodegen/settings.yml, .xcodegen/dependencies.yml]
