name: Build and Test

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:  
  build-and-test:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v1
    - uses: maxim-lobanov/setup-xcode@v1
      with:
        xcode-version: '15.4'
    - name: Logs
      run: |
        /usr/bin/xcodebuild -version
        xcrun swift -version
    - name: Install Dependencies
      run: |
        ./.scripts/installBrewDependencyIfNeeded.sh xcbeautify xcodegen swiftlint swiftgen
    - name: Unit Tests
      run: |
        make -f .ci-cd/build_and_test.mk -B unit_tests
    - name: UI Tests
      run: |
        make -f .ci-cd/build_and_test.mk -B ui_tests
    - name: Prepare xcresult
      if: always()
      run: |
        ls -la Results
        xcrun xcresulttool merge Results/*.xcresult --output-path result.xcresult
    - uses: actions/upload-artifact@v3
      if: failure()
      with:
        name: UITestsSnapshots
        path: UITestsSnapshots
    - name: Run Danger
      if: always()
      run: |
        bundle install
        bundle exec danger
      env:
        DANGER_GITHUB_API_TOKEN: ${{ secrets.DANGER_GITHUB_API_TOKEN }}
